on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3