name: 'Discord Announcement'

on:
  release:
    types: [released]

jobs:
  discrod:
    name: Discord - notify on every release
    runs-on: ubuntu-latest
    steps:
      - name: Convert markdown to discord markdown for issue
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        id: markdown
        with:
          text: "${{github.event.release.tag_name}} \n ${{ github.event.release.body }}"

      - name: Remove links
        run: |
          echo "text=$(echo ${{steps.markdown.outputs.text}} | sed 's/[\w \W \s]*[(]*http[s]*[a-zA-Z0-9 : \. \/ ; % \W -]*[)]*/ /g')" >> $GITHUB_ENV

      - name: send custom message with args
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#0187A6"
          username: "Patch Note !"
          args: ${{env.text}}