on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Conventional Changelog Action
        uses: labor-digital/conventional-release-action@master