on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'composer.json'

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows
      - name: Release to GitHub
        working-directory: ./.github/workflows
        run: npx semantic-release